### ISSUE TITLE
The ids attribute

### ISSUE THREAD

**Issue by LeartS** [nbessi/odoo_new_api_guideline#26]
https://github.com/nbessi/odoo_new_api_guideline/blob/master/source/environment.rst#the-ids-attribute

> The ids attribute is a special attribute of RecordSet. It will be return even if there is more than one Record in RecordSet

What does that mean?

**Comment by nbessi** [comment]
Hello, 


On a RecorSet with many records calling `record_set.ids` will work and not raise an exception.
Doing the same on an other columns/property of the RecordSet will raise an exception as it will violate `ensure_one` constraint

Regards
