### ISSUE TITLE
Add section about _inherits being replaced by fields.Many2one(comodel_name='...', delegate=True)

### ISSUE THREAD

**Issue by red15** [nbessi/odoo_new_api_guideline#27]
This becomes apparent from [the code in fields.py](https://github.com/odoo/odoo/blob/8.0/openerp/fields.py#L1435)

I have been experimenting with this and it seems to work fine.
An example how `product.product` inheritance on `product.template` could work:

```python
class ProductProduct(models.Model):
    _name = 'product.product'

    product_tmpl_id = fields.Many2one(
        comodel_name='product.template', string='Template', delegate=True
    )
```

**Comment by nbessi** [comment]
Notice added

Thanks.
